//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBOCLASS.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MSSQL_Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MSSQL_Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBOCLASS.Resource.MSSQL_Queries", typeof(MSSQL_Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(MAX(OnHandQty),0) 
        ///FROM OBBQ T0 JOIN OBIN T1 ON T0.BinAbs = T1.AbsEntry AND T0.WhsCode = T1.WhsCode
        ///	JOIN OBTN T2 ON T0.SnBMDAbs = T2.AbsEntry
        ///WHERE T0.ItemCode = &apos;{0}&apos;
        ///	AND T2.DistNumber = &apos;{1}&apos;
        ///	AND T1.BinCode = &apos;{2}&apos;.
        /// </summary>
        internal static string OBBQ_GET_ONHAND_QTY {
            get {
                return ResourceManager.GetString("OBBQ_GET_ONHAND_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(MAX(T0.Quantity),0) 
        ///FROM OBTQ T0 JOIN OBTN T1 ON T0.MdAbsEntry = T1.AbsEntry
        ///WHERE T0.ItemCode = &apos;{0}&apos;
        ///	AND T0.WhsCode = &apos;{2}&apos;
        ///	AND T1.DistNumber = &apos;{1}&apos;.
        /// </summary>
        internal static string OBTQ_GET_ONHAND_QTY {
            get {
                return ResourceManager.GetString("OBTQ_GET_ONHAND_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;ObjType&quot;, T0.&quot;DocEntry&quot;, T0.&quot;LineNum&quot;, T0.&quot;VisOrder&quot;, T0.&quot;OpenQty&quot; 
        ///FROM {0}1 T0
        ///WHERE T0.&quot;DocEntry&quot; IN ({1}) and T0.&quot;U_wstock&quot; &gt; 0
        ///ORDER BY T0.&quot;DocEntry&quot;, T0.&quot;VisOrder&quot;.
        /// </summary>
        internal static string OPKL_GET_BASE_LINES {
            get {
                return ResourceManager.GetString("OPKL_GET_BASE_LINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @WMSTransId NVARCHAR(150) = &apos;{0}&apos;
        ///DECLARE @LineWMSTransId NVARCHAR(150) = &apos;{1}&apos;
        ///SELECT T0.DocStatus, T1.DocEntry, T1.LineNum 
        ///FROM ORDN T0 JOIN RDN1 T1 ON T0.DocEntry = T1.DocEntry
        ///WHERE T0.CANCELED = &apos;N&apos;
        ///	AND T0.U_AXC_EXTID = @WMSTransId
        ///	AND (
        ///		CAST(T1.U_AXC_EXTID AS NVARCHAR(MAX)) = @LineWMSTransId				--Exact Match
        ///		OR REPLACE(CAST(T1.U_AXC_EXTID AS NVARCHAR(MAX)),&apos; &apos;,&apos;&apos;) LIKE @LineWMSTransId + &apos;;%&apos;	--Starts with
        ///		OR REPLACE(CAST(T1.U_AXC_EXTID AS NVARCHAR(MAX)),&apos; &apos;,&apos;&apos;) LIKE &apos;%;&apos; + @L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ORDN_GET_BASE_INFO_BY_WMS_ID {
            get {
                return ResourceManager.GetString("ORDN_GET_BASE_INFO_BY_WMS_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(MAX(OnHandQty),0) 
        ///FROM OSBQ T0 JOIN OBIN T1 ON T0.BinAbs = T1.AbsEntry AND T0.WhsCode = T1.WhsCode
        ///	JOIN OSRN T2 ON T0.SnBMDAbs = T2.AbsEntry
        ///WHERE T0.ItemCode = &apos;{0}&apos;
        ///	AND T2.DistNumber = &apos;{1}&apos;
        ///	AND T1.BinCode = &apos;{2}&apos;.
        /// </summary>
        internal static string OSBQ_GET_ONHAND_QTY {
            get {
                return ResourceManager.GetString("OSBQ_GET_ONHAND_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(MAX(T0.Quantity),0) 
        ///FROM OSRQ T0 JOIN OSRN T1 ON T0.MdAbsEntry = T1.AbsEntry
        ///WHERE T0.ItemCode = &apos;{0}&apos;
        ///	AND T0.WhsCode = &apos;{2}&apos;
        ///	AND T1.DistNumber = &apos;{1}&apos;.
        /// </summary>
        internal static string OSRQ_GET_ONHAND_QTY {
            get {
                return ResourceManager.GetString("OSRQ_GET_ONHAND_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(MAX(&quot;Status&quot;),&apos;&apos;) FROM OWOR WHERE &quot;DocEntry&quot; = {0}.
        /// </summary>
        internal static string OWOR_GET_DOC_STATUS {
            get {
                return ResourceManager.GetString("OWOR_GET_DOC_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @WMSTransId NVARCHAR(150) = &apos;{0}&apos;
        ///DECLARE @LineWMSTransId NVARCHAR(150) = &apos;{1}&apos;
        ///SELECT T0.DocStatus, T1.DocEntry, T1.LineNum 
        ///FROM OWTQ T0 JOIN WTQ1 T1 ON T0.DocEntry = T1.DocEntry
        ///WHERE T0.CANCELED = &apos;N&apos;
        ///	AND T0.U_AXC_EXTID = @WMSTransId
        ///	AND (
        ///		CAST(T1.U_AXC_EXTID AS NVARCHAR(MAX)) = @LineWMSTransId				--Exact Match
        ///		OR REPLACE(CAST(T1.U_AXC_EXTID AS NVARCHAR(MAX)),&apos; &apos;,&apos;&apos;) LIKE @LineWMSTransId + &apos;;%&apos;	--Starts with
        ///		OR REPLACE(CAST(T1.U_AXC_EXTID AS NVARCHAR(MAX)),&apos; &apos;,&apos;&apos;) LIKE &apos;%;&apos; + @L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OWTQ_GET_BASE_INFO_BY_WMS_ID {
            get {
                return ResourceManager.GetString("OWTQ_GET_BASE_INFO_BY_WMS_ID", resourceCulture);
            }
        }
    }
}
